name: sangyaw_app
version: 1.1.4
publish_to: none
description: My Sangyaw Application.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  autocomplete_textfield: 1.7.3
  dropdownfield: 1.0.3
  http: ^0.12.0+3
  provider: ^4.1.3
  redux: ^4.0.0+3
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  flutter_spinkit: ^4.1.2
  material_design_icons_flutter: ^4.0.5555
  photo_view: 0.10.2
  intl: ^0.16.1
  screenshot: ^0.2.0
  image_picker: ^0.6.7+7
  dio: ^3.0.10
  cached_network_image: ^2.3.1
  cupertino_icons: ^0.1.3
  date_time_format: ^1.0.0+4
  mime_type: ^0.3.2
  flutter_cache_manager: ^1.4.1
  flutter_form_bloc: ^0.19.0

  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter_icons: 
  image_path_android: assets/images/icon.png
  image_path_ios: assets/images/icon.png
  android: true
  ios: true
flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
