name: sangyaw_app
version: 1.2.0
publish_to: none
description: My Sangyaw Application.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  autocomplete_textfield: 1.7.3
  dropdownfield: 1.0.3
  http: ^0.12.0+3
  provider: ^4.1.3
  redux: ^4.0.0+3
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  redux_logging: ^0.4.0
  flutter_spinkit: ^4.1.2
  material_design_icons_flutter: ^4.0.5555
  photo_view: 0.10.2
  intl: ^0.16.1
  screenshot: ^0.2.0
  image_picker: ^0.6.7+7
  dio: ^3.0.10
  cached_network_image: ^2.3.1
  cupertino_icons: ^0.1.3
  date_time_format: ^1.0.0+4
  mime_type: ^0.3.2
  flutter_form_bloc: ^0.19.0
  path_provider: ^1.6.14
  percent_indicator: ^2.1.6
  sticky_headers: ^0.1.8+1
  uuid: ^2.0.2
  path: ^1.6.4
  sqflite: ^1.1.7+2
  pedantic: ^1.8.0+1
  clock: ^1.0.1
  file: ^5.1.0
  rxdart: '>=0.23.1 <0.25.0'
  url_launcher: ^5.5.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter_icons: 
  image_path_android: assets/images/icon.png
  image_path_ios: assets/images/icon.png
  android: true
  ios: true
flutter: 
  assets: 
    - assets/images/
  uses-material-design: true
